/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String avatar1 = "assets/images/avatar1.png";
  static const String avatar2 = "assets/images/avatar2.png";
  static const String avatar3 = "assets/images/avatar3.png";
  static const String indicator = "assets/icons/indicator.svg";
  static const String indicator1 = "assets/icons/indicator1.svg";
  static const String indicator2 = "assets/icons/indicator2.svg";
  static const String Vector = "assets/icons/Vector.svg";
  static const String voice1 = "assets/icons/voice1.svg";
  static const String voice2 = "assets/icons/voice2.svg";
  static const String voice3 = "assets/icons/voice3.svg";
}
